from __future__ import annotations

from app.services.mumbai_market import enrich_property_market_fields

_RAW_MUMBAI_PROPERTIES = [
    {
        "id": "lnt-elixir-reserve-barbet",
        "title": "L&T Elixir Reserve 2 — Barbet 2BHK",
        "address": "Elixir Reserve, Saki Vihar Road, Powai, Mumbai",
        "city": "Mumbai",
        "locality": "Powai",
        "micro_market": "Central Suburbs",
        "pincode": "400072",
        "property_type": "apartment",
        "transaction_type": "buy",
        "price": 34_200_000,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_sqft": 890,
        "carpet_area_sqft": 890,
        "rera_carpet_area_sqft": 682.44,
        "latitude": 19.1090,
        "longitude": 72.8990,
        "status": "available",
        "availability": "Sample flat viewing slots open this week",
        "possession": "August 2028 (RERA July 2029)",
        "rera_possession": "July 2029",
        "builder_possession": "August 2028",
        "builder": "L&T Realty",
        "year_built": 2029,
        "listing_type": "new_construction",
        "listing_status": "new",
        "current_condition": "sample_flat",
        "who_shows_property": "builder_sales",
        "furnishing": "unfurnished",
        "kitchen_type": "modular",
        "parking": ["car"],
        "price_status": "All-in (lower floors)",
        "google_map_link": "https://www.google.com/maps/search/?api=1&query=Elixir+Reserve+Saki+Vihar+Road+Powai+Mumbai",
        "description": (
            "Tower 6 (Barbet) at L&T Realty's Elixir Reserve 2 — an 8-tower, 11-acre "
            "3B+P1+Lobby+22-storey development on Saki Vihar Road, Powai. Efficient 2BHK "
            "homes with modular kitchen, twin baths, balcony and chajja, set within a "
            "resort-grade amenity podium and the A.M. Naik School campus, moments from the "
            "proposed metro station and the Powai IT/ITES hub."
        ),
        "amenities": [
            "swimming pool", "gym", "lobby", "club house", "garden", "podium garden",
            "kids play area", "indoor play area", "squash court", "pickleball court",
        ],
        "tags": ["new launch", "L&T Realty", "under construction", "metro corridor", "RERA registered"],
        "highlights": [
            "8 towers across an 11-acre land parcel at Powai / Saki Vihar Road",
            "Proposed metro station adjacent to the development",
            "A.M. Naik School within the gated campus",
            "MahaRERA registered: PR1180002500072 (Elixir Reserve T6)",
            "Possession August 2028 (RERA July 2029)",
        ],
        "nearby": {
            "metro": "Proposed metro station adjacent",
            "school": "A.M. Naik School (in-campus)",
            "road": "Saki Vihar Road / JVLR",
            "it_hub": "Powai IT/ITES & SEEPZ",
            "q_commerce": "Blinkit / Zepto within 10 min",
            "airport": "~20 min to T2 (CSMIA)",
        },
        "image_url": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
        "splat_url": "/splats/powai-lake.ksplat",
        "rera_id": "PR1180002500072",
        "occupancy_certificate": False,
        "allotment_letter": True,
        "sale_deed": False,
        "expected_rent_yield": 2.6,
        "walkability_score": 80,
        "commute_score": 84,
    },
    {
        "id": "mumbai-powai-1",
        "title": "Powai Lakeview Smart 3BHK",
        "address": "Hiranandani Gardens, Powai, Mumbai",
        "city": "Mumbai",
        "locality": "Powai",
        "micro_market": "Central Suburbs",
        "property_type": "apartment",
        "price": 31_500_000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area_sqft": 1560,
        "built_up_area_sqft": 1560,
        "latitude": 19.1176,
        "longitude": 72.9060,
        "status": "available",
        "availability": "Today 5:30 PM, Tomorrow 11:00 AM",
        "possession": "Ready to move",
        "builder": "Demo Developer",
        "description": "High-floor lake-facing apartment with morning light, work-from-home den, EV charging, and access to the Hiranandani business district.",
        "amenities": ["lake view", "EV charging", "clubhouse", "work den", "gym", "security"],
        "tags": ["premium", "morning light", "executive", "ready to move", "family"],
        "image_url": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
        "splat_url": "/splats/powai-lake.ksplat",
        "rera_id": "P51800044221",
        "expected_rent_yield": 2.8,
        "walkability_score": 82,
        "commute_score": 78,
    },
    {
        "id": "mumbai-bandra-1",
        "title": "Bandra West Sea-Breeze 2.5BHK",
        "address": "Pali Hill Road, Bandra West, Mumbai",
        "city": "Mumbai",
        "locality": "Bandra",
        "micro_market": "Western Suburbs",
        "property_type": "apartment",
        "price": 66_000_000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area_sqft": 1420,
        "built_up_area_sqft": 1420,
        "latitude": 19.0607,
        "longitude": 72.8296,
        "status": "available",
        "availability": "Tomorrow 4:00 PM, Saturday 10:30 AM",
        "possession": "Ready to move",
        "builder": "Boutique Society",
        "description": "Low-density Bandra home near cafes, schools, seaside walks, and premium retail; strong lifestyle demand with redevelopment tailwinds.",
        "amenities": ["sea breeze", "cafes", "schools nearby", "low density", "covered parking"],
        "tags": ["lifestyle", "walkable", "premium", "redevelopment", "scarce supply"],
        "image_url": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
        "splat_url": "/splats/bandra-west.ksplat",
        "rera_id": "P51800077890",
        "expected_rent_yield": 2.1,
        "walkability_score": 91,
        "commute_score": 75,
    },
    {
        "id": "mumbai-borivali-1",
        "title": "Borivali Redevelopment 2BHK Value Home",
        "address": "Near Borivali West Station, Mumbai",
        "city": "Mumbai",
        "locality": "Borivali",
        "micro_market": "Western Suburbs",
        "property_type": "apartment",
        "price": 18_500_000,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_sqft": 920,
        "built_up_area_sqft": 920,
        "latitude": 19.2290,
        "longitude": 72.8574,
        "status": "available",
        "availability": "Today 7:00 PM, Sunday 12:00 PM",
        "possession": "Under construction",
        "builder": "Redevelopment SPV",
        "description": "Efficient 2BHK in Mumbai's strongest redevelopment micro-market, designed for middle-income buyers who need rail access and resale liquidity.",
        "amenities": ["railway station", "redevelopment", "parking", "security", "efficient layout"],
        "tags": ["value", "redevelopment", "below 5 cr", "high liquidity", "commuter"],
        "image_url": "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80",
        "splat_url": "/splats/borivali-value.ksplat",
        "rera_id": "P51800055901",
        "expected_rent_yield": 3.0,
        "walkability_score": 85,
        "commute_score": 88,
    },
    {
        "id": "mumbai-andheri-1",
        "title": "Andheri East Metro-Connected 2BHK",
        "address": "Marol, Andheri East, Mumbai",
        "city": "Mumbai",
        "locality": "Andheri",
        "micro_market": "Western Suburbs",
        "property_type": "apartment",
        "price": 22_000_000,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_sqft": 980,
        "built_up_area_sqft": 980,
        "latitude": 19.1172,
        "longitude": 72.8826,
        "status": "available",
        "availability": "Tomorrow 2:00 PM, Friday 6:00 PM",
        "possession": "Ready to move",
        "builder": "Metroline Homes",
        "description": "Metro and airport connected apartment with practical floor plan, quick office commute, and strong rental tenant pool.",
        "amenities": ["metro nearby", "airport access", "gym", "rental demand", "security"],
        "tags": ["commute", "rental yield", "below 5 cr", "metro", "working professionals"],
        "image_url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
        "splat_url": "/splats/andheri-east.ksplat",
        "rera_id": "P51800061012",
        "expected_rent_yield": 3.3,
        "walkability_score": 78,
        "commute_score": 92,
    },
    {
        "id": "mumbai-worli-1",
        "title": "Worli Sea-Link Luxury 4BHK",
        "address": "Dr Annie Besant Road, Worli, Mumbai",
        "city": "Mumbai",
        "locality": "Worli",
        "micro_market": "South Central Mumbai",
        "property_type": "apartment",
        "price": 185_000_000,
        "bedrooms": 4,
        "bathrooms": 5,
        "area_sqft": 3200,
        "built_up_area_sqft": 3200,
        "latitude": 19.0176,
        "longitude": 72.8171,
        "status": "reserved",
        "availability": "Next private slot Monday 5:00 PM",
        "possession": "Ready to move",
        "builder": "Luxury Tower",
        "description": "Large-format luxury residence with sea-link views, concierge operations, private lift lobby, and high-end amenities.",
        "amenities": ["sea view", "concierge", "private lift", "club", "valet", "spa"],
        "tags": ["luxury", "above 10 cr", "sea view", "negotiation leverage", "premium"],
        "image_url": "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80",
        "splat_url": "/splats/worli-luxury.ksplat",
        "rera_id": "P51900033044",
        "expected_rent_yield": 1.9,
        "walkability_score": 72,
        "commute_score": 81,
        "risk_flags": ["High inventory bucket; negotiate harder on payment schedule."],
    },
    {
        "id": "mumbai-ghatkopar-1",
        "title": "Ghatkopar East Family 3BHK Near Metro",
        "address": "Pant Nagar, Ghatkopar East, Mumbai",
        "city": "Mumbai",
        "locality": "Ghatkopar",
        "micro_market": "Central Suburbs",
        "property_type": "apartment",
        "price": 32_000_000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area_sqft": 1350,
        "built_up_area_sqft": 1350,
        "latitude": 19.0863,
        "longitude": 72.9080,
        "status": "available",
        "availability": "Today 3:30 PM, Saturday 1:00 PM",
        "possession": "Under construction",
        "builder": "Central Redev Homes",
        "description": "Family-sized home in a redevelopment-active market with metro access, schools, and vegetarian-friendly retail catchment.",
        "amenities": ["metro nearby", "schools nearby", "redevelopment", "market nearby", "clubhouse"],
        "tags": ["family", "metro", "redevelopment", "below 5 cr", "central suburbs"],
        "image_url": "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80",
        "splat_url": "/splats/ghatkopar-family.ksplat",
        "rera_id": "P51800044120",
        "expected_rent_yield": 2.9,
        "walkability_score": 83,
        "commute_score": 86,
    },
    {
        "id": "mumbai-malad-1",
        "title": "Malad West Growth-Corridor 2BHK",
        "address": "Link Road, Malad West, Mumbai",
        "city": "Mumbai",
        "locality": "Malad",
        "micro_market": "Western Suburbs",
        "property_type": "apartment",
        "price": 20_800_000,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_sqft": 1010,
        "built_up_area_sqft": 1010,
        "latitude": 19.1867,
        "longitude": 72.8486,
        "status": "available",
        "availability": "Friday 4:30 PM, Sunday 10:30 AM",
        "possession": "Ready to move",
        "builder": "Westline Realty",
        "description": "Balanced price point near retail, schools, and Link Road; useful for buyers seeking good monthly EMI without losing redevelopment upside.",
        "amenities": ["retail nearby", "schools nearby", "parking", "security", "redevelopment"],
        "tags": ["value", "redevelopment", "below 5 cr", "family", "western suburbs"],
        "image_url": "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80",
        "splat_url": "/splats/malad-west.ksplat",
        "rera_id": "P51800058219",
        "expected_rent_yield": 3.1,
        "walkability_score": 80,
        "commute_score": 79,
    },
    {
        "id": "mumbai-chembur-1",
        "title": "Chembur Garden-View 3BHK",
        "address": "Diamond Garden, Chembur, Mumbai",
        "city": "Mumbai",
        "locality": "Chembur",
        "micro_market": "Harbour/Central",
        "property_type": "apartment",
        "price": 42_000_000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area_sqft": 1680,
        "built_up_area_sqft": 1680,
        "latitude": 19.0522,
        "longitude": 72.9005,
        "status": "available",
        "availability": "Saturday 11:00 AM, Sunday 5:30 PM",
        "possession": "Ready to move",
        "builder": "Garden District Homes",
        "description": "Large carpet efficiency, green outlook, family-oriented society, and quick access to BKC via Eastern Freeway/SCLR.",
        "amenities": ["green view", "family society", "BKC access", "parking", "clubhouse"],
        "tags": ["family", "green", "below 5 cr", "commute", "quiet"],
        "image_url": "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80",
        "splat_url": "/splats/chembur-garden.ksplat",
        "rera_id": "P51800049888",
        "expected_rent_yield": 2.7,
        "walkability_score": 76,
        "commute_score": 84,
    },
]

SAMPLE_PROPERTIES = [enrich_property_market_fields(item) for item in _RAW_MUMBAI_PROPERTIES]
