import type { MarketInsights, Property } from "@/lib/api";

export const DEMO_PROPERTIES: Property[] = [
  {
    id: "demo-powai-1",
    title: "Powai Lakeview Smart 3BHK",
    address: "Hiranandani Gardens, Powai, Mumbai",
    city: "Mumbai",
    locality: "Powai",
    micro_market: "Central Suburbs",
    property_type: "apartment",
    transaction_type: "buy",
    price: 31500000,
    price_per_sqft: 20192,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 1560,
    built_up_area_sqft: 1560,
    latitude: 19.1176,
    longitude: 72.906,
    status: "available",
    availability: "Today 5:30 PM, Tomorrow 11:00 AM",
    possession: "Ready to move",
    builder: "Demo Developer",
    description: "High-floor lake-facing apartment with morning light, work-from-home den, EV charging, and access to the Hiranandani business district.",
    amenities: ["lake view", "EV charging", "clubhouse", "work den", "gym", "security"],
    tags: ["premium", "morning light", "executive", "ready to move"],
    image_url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
    rera_id: "P51800044221",
    score: 0.94,
    inventory_months: 13,
    cost_bucket: "5-10 cr",
    redevelopment_score: 72,
    redevelopment_das_signed: 288,
    construction_cost_low: 3510000,
    construction_cost_high: 4680000,
    emi_20y_per_lakh: 836,
    monthly_emi_estimate: 210672,
    expected_rent_yield: 2.8,
    walkability_score: 82,
    commute_score: 78,
    risk_flags: [],
  },
  {
    id: "demo-bandra-1",
    title: "Bandra West Sea-Breeze 2.5BHK",
    address: "Pali Hill Road, Bandra West, Mumbai",
    city: "Mumbai",
    locality: "Bandra",
    micro_market: "Western Suburbs",
    property_type: "apartment",
    transaction_type: "buy",
    price: 66000000,
    price_per_sqft: 46479,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 1420,
    built_up_area_sqft: 1420,
    latitude: 19.0607,
    longitude: 72.8296,
    status: "available",
    availability: "Tomorrow 4:00 PM, Saturday 10:30 AM",
    possession: "Ready to move",
    builder: "Boutique Society",
    description: "Low-density Bandra home near cafes, schools, seaside walks, and premium retail; strong lifestyle demand with redevelopment tailwinds.",
    amenities: ["sea breeze", "cafes", "schools nearby", "low density", "covered parking"],
    tags: ["lifestyle", "walkable", "premium", "redevelopment"],
    image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    rera_id: "P51800077890",
    score: 0.9,
    inventory_months: 16,
    cost_bucket: "5-10 cr",
    redevelopment_score: 88,
    redevelopment_das_signed: 399,
    construction_cost_low: 3195000,
    construction_cost_high: 4260000,
    emi_20y_per_lakh: 836,
    monthly_emi_estimate: 441408,
    expected_rent_yield: 2.1,
    walkability_score: 91,
    commute_score: 75,
    risk_flags: [],
  },
  {
    id: "demo-andheri-1",
    title: "Andheri East Metro-Connected 2BHK",
    address: "Marol, Andheri East, Mumbai",
    city: "Mumbai",
    locality: "Andheri",
    micro_market: "Western Suburbs",
    property_type: "apartment",
    transaction_type: "buy",
    price: 22000000,
    price_per_sqft: 22449,
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 980,
    built_up_area_sqft: 980,
    latitude: 19.1172,
    longitude: 72.8826,
    status: "available",
    availability: "Tomorrow 2:00 PM, Friday 6:00 PM",
    possession: "Ready to move",
    builder: "Metroline Homes",
    description: "Metro and airport connected apartment with practical floor plan, quick office commute, and strong rental tenant pool.",
    amenities: ["metro nearby", "airport access", "gym", "rental demand", "security"],
    tags: ["commute", "rental yield", "below 5 cr", "metro"],
    image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    rera_id: "P51800061012",
    score: 0.86,
    inventory_months: 9,
    cost_bucket: "1-5 cr",
    redevelopment_score: 81,
    redevelopment_das_signed: 399,
    construction_cost_low: 2205000,
    construction_cost_high: 2940000,
    emi_20y_per_lakh: 836,
    monthly_emi_estimate: 147136,
    expected_rent_yield: 3.3,
    walkability_score: 78,
    commute_score: 92,
    risk_flags: [],
  },
  {
    id: "demo-worli-1",
    title: "Worli Sea-Link Luxury 4BHK",
    address: "Dr Annie Besant Road, Worli, Mumbai",
    city: "Mumbai",
    locality: "Worli",
    micro_market: "South Central Mumbai",
    property_type: "apartment",
    transaction_type: "buy",
    price: 185000000,
    price_per_sqft: 57812,
    bedrooms: 4,
    bathrooms: 5,
    area_sqft: 3200,
    built_up_area_sqft: 3200,
    latitude: 19.0176,
    longitude: 72.8171,
    status: "reserved",
    availability: "Next private slot Monday 5:00 PM",
    possession: "Ready to move",
    builder: "Luxury Tower",
    description: "Large-format luxury residence with sea-link views, concierge operations, private lift lobby, and high-end amenities.",
    amenities: ["sea view", "concierge", "private lift", "club", "valet", "spa"],
    tags: ["luxury", "above 10 cr", "sea view", "negotiation leverage"],
    image_url: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80",
    rera_id: "P51900033044",
    score: 0.82,
    inventory_months: 22,
    cost_bucket: "10 cr+",
    redevelopment_score: 65,
    redevelopment_das_signed: 118,
    construction_cost_low: 7200000,
    construction_cost_high: 9600000,
    emi_20y_per_lakh: 836,
    monthly_emi_estimate: 1237280,
    expected_rent_yield: 1.9,
    walkability_score: 72,
    commute_score: 81,
    risk_flags: ["High inventory bucket; negotiate harder on payment schedule."],
  },
];

export const DEMO_MARKET_INSIGHTS: MarketInsights = {
  city: "Mumbai",
  inventory_by_price_bucket: [
    { cost_range: "1-2 cr", annual_sales_units: 8200, unsold_units: 6800, months_inventory: 10 },
    { cost_range: "2-5 cr", annual_sales_units: 9400, unsold_units: 11200, months_inventory: 14 },
    { cost_range: "5-10 cr", annual_sales_units: 3200, unsold_units: 5200, months_inventory: 20 },
  ],
  redevelopment: {
    development_agreements_signed_total: 910,
    period: "2024-2025 demo baseline",
    yoy_growth_2024_2025_pct: 18,
    top_micro_markets: { Borivali: 142, Andheri: 118, Bandra: 94, Ghatkopar: 83, Powai: 62 },
    expected_housing_units: 44000,
    land_unlocked_acres: 310,
  },
  construction_cost_guide: { good: "INR 2,250-3,000/sq ft", premium: "INR 3,500-5,000/sq ft" },
  home_loan_reference: { annual_rate_pct: 8, tenure_years: 20, emi_per_lakh: 836 },
  recommendations: [
    "Prioritize metro-linked western and central suburbs for liquidity.",
    "Use inventory months to shape negotiation posture.",
    "Recheck lender rates before final affordability advice.",
  ],
};

export function searchDemoProperties(query: string, limit = 8) {
  const tokens = query.toLowerCase().split(/\s+/).filter(Boolean);
  return [...DEMO_PROPERTIES]
    .map((property) => {
      const corpus = `${property.title} ${property.locality} ${property.description} ${property.tags.join(" ")} ${property.amenities.join(" ")}`.toLowerCase();
      const score = tokens.reduce((sum, token) => sum + (corpus.includes(token) ? 1 : 0), 0) + Number(property.score || 0);
      return { property: { ...property, score }, score };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((item) => item.property);
}
